trigger: none

pr:
  - master

pool:
 vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Debug'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.101'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

