trigger: none

pr:
    branches:
         include:
         - master
    paths:
          exclude:
          - README.md
          - Scripts/*

pool:
 vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Debug'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    configuration: '$(buildConfiguration)'
